### ISSUE TITLE
Filter by e10s

### ISSUE THREAD

**Issue by vitillo** [Yoric/are-we-shutting-down-yet-#14]
It would be great to have a side view that allows to compare e10s vs non e10s.

**Comment by Yoric** [comment]
I can provide a filter that lets us look at only e10s/only non-e10s. Would that be sufficient?

**Comment by vitillo** [comment]
Yes, it would.

**Comment by Yoric** [comment]
I just pushed a change that lets us do that. No UX yet.

By default, AWSDY still displays regardless of e10s. To display only e10s crashes, add search param `e10s=true`. To display without any e10s crash, add search param `e10s=false`.

I'll try and add a UX when I find time.
